### ISSUE TITLE
As a player, I want to be able to unselect a star or carrier that I have currently selected on the map

### ISSUE THREAD

**Issue by mike-eason** [solaris-games/solaris#186]
- Players may click on a star and then click away (in a blank space of the map) to unselect.

**Comment by mike-eason** [comment]
Need to asses the value of this story. Maybe it isn't needed anymore?

**Comment by belongkl-baesys** [comment]
I would definitely make use of this feature heavily, but I feel like it would be best suited as a game option so mobile players wouldn't be adversely affected.

**Comment by mike-eason** [comment]
Understood, thanks @belongkl-baesys
