### ISSUE TITLE
As a player, I want to be notified when a carrier is launched against me or when a carrier combat occurs

### ISSUE THREAD

**Issue by mike-eason** [solaris-games/solaris#267]

**Comment by T4G2** [comment]
I suggest this will be true only when you turn on notification or so ...

**Comment by mike-eason** [comment]
@T4G2 Absolutely, all emails sent should check the accounts' email notification setting.

We may need to extend the notifications to that player can pick and choose which notifications they want to receive, but that is another issue entirely.
