### ISSUE TITLE
The game UI runs slow in Palemoon and Basilisk browsers

### ISSUE THREAD

**Issue by l29ah** [solaris-games/solaris#567]
When a game is opened in a browser, it consumes 100% CPU regardless of what's happening. This hurts battery life a lot.

**Comment by mike-eason** [comment]
Hello,

Can you provide some more details?

- You browser and version
- Does this occur on all games or just one in particular?

You can also try the following to help improve performance:

- Use Single Ring natural resources
- Voronoi territory style
- Turn off Nebula density

You can find the above settings in the game menu -> Options.

**Comment by l29ah** [comment]
Occurs both on palemoon-28.17.0 and basilisk-2021.01.05. All games.
Tried that, CPU consumption didn't become any lower.

**Comment by mike-eason** [comment]
@l29ah I have tried it with Palemoon and Firefox I'm getting around 80% CPU usage.

Palemoon certainly isn't a browser I've considered for support. Solaris is developed primarily for Chrome as it has the highest market share, I have barely looked into the other big browsers (Edge, Firefox, Safari). I suggest switching to that browser in the meantime until a fix is implemented.

**Comment by l29ah** [comment]
It's the same in firefox-85.0.

**Comment by l29ah** [comment]
Also tested with qutebrowser that's based on chromium, and it doesn't consume much CPU.

**Comment by Kurtzmusch** [comment]
firefox browsers webgl implementation appears to be broken on linux and it's been a problem for a decade now

**Comment by LevitatingBusinessMan** [comment]
@Kurtzmusch Crazy, I was just now compiling palemoon to check this issue out.

**Comment by LevitatingBusinessMan** [comment]
I have tested on Palemoon 29.1.1 and I don't have any performance issues.
However we are working on performance improvements which could help you out.


Did find an issue with font spacing:
https://i.imgur.com/Cc1l3pQ.png

I also tried firefox, and I also had no performance issues, though it was certainly less smooth. However this is probably due to Firefox limiting the JS vm somewhat, as it often does. My cpu didn't go above 50% with Firefox.

**Comment by Kurtzmusch** [comment]
@LevitatingBusinessMan did you measure fps with the devel version? i get 1/10th the fps i get on chrome... i also have tryed several combinations on the about:config

**Comment by Kurtzmusch** [comment]
it's been a long time since i updated mesa though...

**Comment by LevitatingBusinessMan** [comment]
@Kurtzmusch I played around with the 32p game

In order from smoothest to less smoothest: Chromium, Firefox, Palemoon
Minimun fps:
Chromium: 70
Palemoon: 40
Firefox: 30

Definitely playable even on Palemoon
